### ISSUE TITLE
incorrectly indent some files

### ISSUE THREAD

**Issue by penhoi** [Vimjas/vim-python-pep8-indent#62] opened 2016-10-10 02:19 UTC
Current version fails to indent some files. As an instance, i attach a file that triggers this failure.
[scheduler.py.zip](https://github.com/hynek/vim-python-pep8-indent/files/518724/scheduler.py.zip)

**Comment by purpleP** [comment] 2017-03-10 13:03
@penhoi Instead of posting a file I think it would be more beneficial if you would make small test case where indent fails.

**Comment by blueyed** [comment] 2018-07-15 19:21
Closing as possible duplicate of #97.

**Closed by blueyed** 2018-07-15 19:21 UTC
